Repository josh-development/core, pull requests merged in 2022-04, with the labels that each got.

#61 chore(deps): update
  package.json
  yarn.lock
Labels: Meta: Dependencies, Priority: Low, SEM: N/A, Status: Review Ready, Type: Maintenance

#55 chore(eslint): refactor rules
  .eslintrc
  src/lib/errors/JoshError.ts
  src/lib/errors/JoshProviderError.ts
  src/lib/structures/Josh.ts
  src/lib/structures/default-provider/MapProvider.ts
  tests/lib/structures/default-provider/MapProvider.test.ts
Labels: Priority: Low, SEM: N/A, Status: Review Ready, Type: Consistency

#57 refactor: providers and errors
  .vscode/settings.json
  package.json
  src/lib/functions/index.ts
  src/lib/functions/resolveCommonIdentifier.ts
  src/lib/functions/validators/payloads/WithData.ts
  src/lib/functions/validators/payloads/index.ts
  src/lib/structures/Josh.ts
  src/lib/structures/JoshProvider.ts
  src/lib/structures/default-provider/MapProvider.ts
  src/lib/types/CommonIdentifiers.ts
  src/lib/types/index.ts
  tests/lib/structures/default-provider/MapProvider.test.ts
  yarn.lock
Labels: Meta: Error Handling, Meta: Refactor, Priority: Medium, SEM: Major, Status: Review Ready, Type: Consistency

#54 refactor: middleware
  package.json
  rollup.bundle.ts
  src/index.ts
  src/lib/decorators/ApplyMiddlewareOptions.ts
  src/lib/decorators/PostProvider.ts
  src/lib/decorators/PreProvider.ts
  src/lib/decorators/index.ts
  src/lib/structures/Josh.ts
  src/lib/structures/Middleware.ts
  src/lib/structures/MiddlewareStore.ts
  src/lib/types/BuiltInMiddleware.ts
  src/lib/types/index.ts
  src/middlewares/AutoEnsure.ts
  yarn.lock
Labels: Meta: Refactor, Priority: Medium, SEM: Major, Status: Review Ready, Type: Enhancement

#60 feat: add Josh#each() method
  src/lib/structures/Josh.ts
  src/lib/structures/JoshProvider.ts
  src/lib/structures/Middleware.ts
  src/lib/structures/default-provider/MapProvider.ts
  src/lib/types/Method.ts
  src/lib/types/Payload.ts
  src/lib/types/Payloads.ts
  tests/lib/structures/default-provider/MapProvider.test.ts
Labels: Meta: Feature, Priority: Low, SEM: Minor, Status: Review Ready

#62 feat: refactor key-path system
  src/lib/structures/Josh.ts
  tests/lib/structures/Josh.test.ts
Labels: Meta: Feature, Meta: Refactor, Priority: High, SEM: Major, Status: Review Ready
